- fact_table: SAMPLE_FACT.fact_sales
  fk_column: dim_customer_key
  dim_table: SAMPLE_DIM.dim_customer
  dim_column: customer_key
  confidence: high
  confidence_score: 0.9571428571428571
  method: name_pattern
- fact_table: SAMPLE_FACT.fact_sales
  fk_column: dim_date_key
  dim_table: SAMPLE_DIM.dim_date
  dim_column: date_key
  confidence: high
  confidence_score: 0.94
  method: name_pattern
- fact_table: SAMPLE_FACT.fact_sales
  fk_column: dim_product_key
  dim_table: SAMPLE_DIM.dim_product
  dim_column: product_key
  confidence: high
  confidence_score: 0.9538461538461538
  method: name_pattern
- fact_table: SAMPLE_FACT.fact_sales
  fk_column: dim_store_key
  dim_table: SAMPLE_DIM.dim_store
  dim_column: store_key
  confidence: high
  confidence_score: 0.9454545454545455
  method: name_pattern
- fact_table: FACT.FACT_SALES
  fk_column: DIM_CUSTOMER_KEY
  dim_table: DIM.DIM_CUSTOMER
  dim_column: CUSTOMER_KEY
  confidence: high
  confidence_score: 0.9571428571428571
  method: name_pattern
- fact_table: FACT.FACT_SALES
  fk_column: DIM_DATE_KEY
  dim_table: DIM.DIM_DATE
  dim_column: DATE_KEY
  confidence: high
  confidence_score: 0.94
  method: name_pattern
- fact_table: FACT.FACT_SALES
  fk_column: DIM_PRODUCT_KEY
  dim_table: DIM.DIM_PRODUCT
  dim_column: PRODUCT_KEY
  confidence: high
  confidence_score: 0.9538461538461538
  method: name_pattern
- fact_table: FACT.FACT_SALES
  fk_column: DIM_STORE_KEY
  dim_table: DIM.DIM_STORE
  dim_column: STORE_KEY
  confidence: high
  confidence_score: 0.9454545454545455
  method: name_pattern
